# TensorFlow Syntax Basic

In [2]:
import tensorflow as tf

In [3]:
print(tf.__version__)

1.14.0


In [4]:
hello = tf.constant("Hello ")

In [5]:
world = tf.constant("World")

In [6]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [7]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [8]:
with tf.Session() as sess:
    result = sess.run(hello + world)

In [9]:
print(result)

b'Hello World'


In [10]:
a = tf.constant(10)
b = tf.constant(20)

with tf.Session() as sess:
    result = sess.run(a + b)

In [11]:
result

30

In [12]:
const = tf.constant(10)

In [17]:
fill_mat = tf.fill((4, 4), 10)

In [18]:
myzeros = tf.zeros((4, 4))

In [19]:
myones = tf.ones((4, 4))

In [20]:
myrandn = tf.random_normal((4, 4), mean=0, stddev=1.0)

In [21]:
myrandu = tf.random_uniform((4, 4), minval=0, maxval=1)

In [22]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [23]:
sess = tf.InteractiveSession() # Better for jupyter notebook (but not for development)

In [26]:
for op in my_ops:
    print(op.eval()) # The same as: print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 1.44573    -0.23058288  1.4589183  -0.05951897]
 [-0.25583127  0.10166255  1.4833462  -0.8688002 ]
 [ 0.5660178  -0.24558659 -1.2039971  -0.73405147]
 [ 0.58470833  0.05989617  0.36817408  1.163921  ]]


[[0.44893372 0.2023269  0.70646775 0.92804444]
 [0.9276997  0.5914521  0.38138545 0.40893078]
 [0.27462184 0.63221574 0.5498544  0.6497816 ]
 [0.99490213 0.30365992 0.2724185  0.564955  ]]


