In [1]:
import numpy as np


In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0,100,(10,2))

In [4]:
data

array([[50, 71],
       [17,  6],
       [ 3, 27],
       [68, 53],
       [36, 63],
       [ 3, 55],
       [22, 78],
       [61, 71],
       [14, 78],
       [65, 74]])

In [5]:
scaler_model = MinMaxScaler()

In [6]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [7]:
scaler_model.fit(data)

/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [8]:
scaler_model.transform(data)

array([[0.72307692, 0.90277778],
       [0.21538462, 0.        ],
       [0.        , 0.29166667],
       [1.        , 0.65277778],
       [0.50769231, 0.79166667],
       [0.        , 0.68055556],
       [0.29230769, 1.        ],
       [0.89230769, 0.90277778],
       [0.16923077, 1.        ],
       [0.95384615, 0.94444444]])

In [9]:
scaler_model.fit_transform(data)

/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0.72307692, 0.90277778],
       [0.21538462, 0.        ],
       [0.        , 0.29166667],
       [1.        , 0.65277778],
       [0.50769231, 0.79166667],
       [0.        , 0.68055556],
       [0.29230769, 1.        ],
       [0.89230769, 0.90277778],
       [0.16923077, 1.        ],
       [0.95384615, 0.94444444]])

In [11]:
import pandas as pd

In [12]:
my_data = np.random.randint(0,101,(50,4))

In [14]:
my_data

array([[ 76,  58,  61,  53],
       [ 87,  31,  21,  37],
       [ 24,  64,  58,  25],
       [ 44,  10,  64,  82],
       [ 86,  23,  69,  57],
       [ 69,  81,  75,   0],
       [ 85,  71,  30,  99],
       [ 42,  56,  45,  93],
       [ 43,  55,  77,  71],
       [ 70,  12,  53,  52],
       [ 20,  67,  58,  93],
       [100,  11,   2,  49],
       [ 95,  32,  13,  98],
       [ 24,  88,  27,  61],
       [ 19,  66,  55,  18],
       [ 50,   7,  23,  59],
       [ 46,  77,  73,  80],
       [ 43,  63,   4,  29],
       [ 13,  47,  98,  91],
       [ 13,   5,  92,   7],
       [ 82,  28,  67,  13],
       [  3,  28,  88,  26],
       [ 82,  11,  65,  74],
       [ 12,  31,  92,  78],
       [ 25,  31,  18,   8],
       [ 73,  61,  77,  98],
       [ 10,  21,  21,  88],
       [ 24,   5,  58,  50],
       [  4,   0,  63,  56],
       [ 48,  72,   7,  52],
       [ 54,  79,  73,  92],
       [ 98,  75,  82,  15],
       [ 79,  81,  15,  81],
       [ 42,  24,  48,  88],
       [ 57,  

In [19]:
df = pd.DataFrame(data=my_data,columns=['f1','f2','f3','label'])

In [20]:
df

f1  f2  f3  label
0    76  58  61     53
1    87  31  21     37
2    24  64  58     25
3    44  10  64     82
4    86  23  69     57
5    69  81  75      0
6    85  71  30     99
7    42  56  45     93
8    43  55  77     71
9    70  12  53     52
10   20  67  58     93
11  100  11   2     49
12   95  32  13     98
13   24  88  27     61
14   19  66  55     18
15   50   7  23     59
16   46  77  73     80
17   43  63   4     29
18   13  47  98     91
19   13   5  92      7
20   82  28  67     13
21    3  28  88     26
22   82  11  65     74
23   12  31  92     78
24   25  31  18      8
25   73  61  77     98
26   10  21  21     88
27   24   5  58     50
28    4   0  63     56
29   48  72   7     52
30   54  79  73     92
31   98  75  82     15
32   79  81  15     81
33   42  24  48     88
34   57  63  27     15
35   81  82  12      9
36   61  28  65     26
37   46  61  88    100
38   85  43  53     45
39   10   0  67     99
40   92  52  39     15
41   38  96  63     61
42   92  77  27     41
43   51  89   9     24
44   66  97  30     64
45   74  31  98     19
46   70  22  40     15
47   52  49  60      2
48   89  50  73     28
49   51  17  61     31

In [24]:
x = df[['f1','f2','f3']]

In [25]:
y = df['label']

In [26]:
from sklearn.model_selection import train_test_split

In [29]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=101)

In [30]:
x_train.shape

(35, 3)

In [31]:
x_test.shape

(15, 3)

In [32]:
y_train.shape

(35,)

In [33]:
y_train.shape

(35,)